---
# Общие переменные
system_packages:
  - git
  - curl
  - wget
  - nano
  - htop
  - net-tools
  - tree
  - jq
  - unzip
  - gnupg
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - python3-pip
  - python3-venv
  - ufw
  - strongswan
  - xl2tpd
  - nginx
  - ssh

docker_users:
  - "{{ ansible_user_id }}"