FROM python:3.12-slim

WORKDIR /app

#Зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#Код
COPY . .

#Порт
EXPOSE 8000

#Запуск
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
