---
- name: Установка Docker и Docker Compose
  hosts: devops_servers
  become: yes
  tasks:
    - name: Настройка UFW
      ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - 22    #ssh
        - 80    #HTTP
        - 443   #HTTPS
        - 500   #IKEv2/IPSec
        - 4500  #NAT-T IPSec
        - 1701  #L2TP
    - name: Включить UFW
      ufw:
        state: enabled
        policy: deny